fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

my:
    resource: "@MyBundle/Controller/"
    type:     annotation
    prefix:   /mine

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
